apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: total-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # Request cert-manager to use the issuer just created
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Automatically redirect from HTTP to HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - tungha104.id.vn # Change here
    secretName: mindx-app-tls
  rules:
  - host: tungha104.id.vn # Change here
    http:
      paths:
      # Routing for API
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 3000
      # Routing for Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 8080